---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: src/content
  label: Pages
  create: all
  match: "*"
  exclude: _index.md
- type: directory
  path: src/content/alumni
  label: Alumni
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - alumnus
- type: directory
  path: src/content/members
  label: Members
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - member
- type: directory
  path: src/content/refs
  label: References
  create: documents
  match: "**/*"
  exclude: _index.md
upload_dir: src/static/images
public_path: images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.49.2
